#this project yaml file is designed for https://github.com/anxolerd/dvpwa application to use the application config file is needed to be changed for that certain application.the path on which it will work is needed to be same.
entrypoints:
  - dvpwa/run.py                  # DVPWA example
  # - server.py
  # - cli/main.py
  # - workers/celery_worker.py

exclude_dirs:
  - __pycache__
  - .git
  - tests
  - venv
  - migrations

exclude_files:
  - test_*.py
  - "*_test.py"
